[package]
name = "lib_test"
version = "0.1.0"
authors = ["mr47hsy <824852163@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "callrust"
crate-type = ["cdylib"]
